title: Greenstag
email: contact@greenstag.im
description: >-
  Greenstag is a development studio exploring sustainable systems through a root cause lens.
baseurl: ""
url: "https://www.greenstag.im"
twitter_username: greenstag-im
github_username:  greenstag-im

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/